name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          S3LIBRARY_ACCESSKEY: ${{ secrets.S3LIBRARY_ACCESSKEY }}
          S3LIBRARY_SECRET: ${{ secrets.S3LIBRARY_SECRET }}
          S3LIBRARY_SERVICEENDPOINT: ${{ vars.S3LIBRARY_SERVICEENDPOINT }}
